### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gleb2372372** [drygdryg/OneShot_Termux_installer#13]
sudo python OneShot/oneshot.py -i wlan0 -K

missing required argument! (use --help for usage)

Android 13 MiUI 14

**Comment by rakib-rock** [comment]
sudo python oneshot.py -i wlan0 -K

Try this one

**Comment by Gleb2372372** [comment]
It's not going to work.

**Comment by Gleb2372372** [comment]
https://github.com/drygdryg/OneShot_Termux_installer/issues/14#issue-2099090240
