### ISSUE TITLE
Linker warning for Pixiewps

### ISSUE THREAD

**Issue by eda-abec** [drygdryg/OneShot_Termux_installer#2]
After the script runs Pixiewps, a warning appears:

```
[*] Running Pixiewps…
WARNING: linker: /data/data/com.termux/files/usr/bin/pixiewps: unsupported flags DT_FLAGS_1=0x8000001
```

It is working fine, just it doesn't look nice and maybe could cause something.

I am using aarch64 in Termux on Android 7.1.2.

This is low priority, I am opening this just for record.

**Comment by drygdryg** [comment]
Fixed in 471865552afe7a6825538014c0092b511250385b
