### ISSUE TITLE
Can't get password after calculating wps pin

### ISSUE THREAD

**Issue by mahrabshaon** [drygdryg/OneShot_Termux_installer#3]
I'm using stock android 9 on arm64 ab device. I installed oneshot successfully. It can calculate the wps pin with pixiewps but can't show the password of the network. On the other side on the same device in a custom rom it can show the password. Help me to use oneshot on any stock android. Many Many thanks. 😀😀

**Comment by drygdryg** [comment]
Duplicate https://github.com/drygdryg/OneShot/issues/51
